- name: "install tmux"
  apt: pkg=tmux state=present

- name: "install mosh"
  apt: pkg=mosh state=present

- name: "install htop"
  apt: pkg=htop state=present

- name: "install stress"
  apt: pkg=stress state=present

- name: "install tcptrack"
  apt: pkg=tcptrack state=present

- name: "install bmon"
  apt: pkg=bmon state=present

- name: "install avahi-daemon"
  apt: pkg=avahi-daemon state=present

- name: "install lsof"
  apt: pkg=lsof state=present

# - name: "install ntp"
#   apt: pkg=ntp state=present

- name: "Set hostname"
  hostname: name="{{ inventory_hostname_short }}"

- name: "add hostname to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    line: '127.0.1.1 {{ inventory_hostname_short }}'

